name: Test
"on":
  push:
    branches:
      - master
      - greenkeeper/**
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Install
        run: npm ci
      - name: Test
        run: npm run lint
